#!/bin/bash
# This script provides instructions for associating a WAF policy with Azure Front Door
# Since the Azure CLI commands for Front Door can change, below are instructions for both CLI and Portal

# Azure CLI Instructions
echo "======================= Azure CLI Instructions ======================="
echo "To associate the WAF policy with Front Door using Azure CLI, try these commands:"
echo ""
echo "# Login to Azure (if not already logged in)"
echo "az login"
echo ""
echo "# Make sure the front-door extension is installed"
echo "az extension add --name front-door"
echo ""
echo "# Try this command syntax first:"
echo "az network front-door waf-policy frontend-endpoint link create \\"
echo "  --resource-group az700-rg001 \\"
echo "  --policy-name az700wafpolicy \\"
echo "  --fd-name az700-frontdoor-demo-20250306 \\"
echo "  --frontend-endpoint-name frontendEndpoint1"
echo ""
echo "# If that doesn't work, try this alternative syntax:"
echo "az network front-door waf-policy link \\"
echo "  --resource-group az700-rg001 \\"
echo "  --policy-name az700wafpolicy \\"
echo "  --fd-name az700-frontdoor-demo-20250306 \\"
echo "  --frontend-endpoint frontendEndpoint1"
echo ""
echo "# If CLI commands continue to have issues, please use the Azure Portal method below"
echo ""
echo "======================= Azure Portal Instructions ======================="
echo "To associate the WAF policy with Front Door using Azure Portal:"
echo ""
echo "1. Go to the Azure Portal (https://portal.azure.com)"
echo "2. Navigate to your Front Door resource: az700-frontdoor-demo-20250306"
echo "3. Click on 'Security policies' in the left menu"
echo "4. Click '+ Associate'"
echo "5. Select the WAF policy: az700wafpolicy"
echo "6. Select the frontend endpoint: frontendEndpoint1"
echo "7. Click 'Add'"
echo "8. Wait for the association to complete"
echo ""
echo "The WAF policy should now be associated with your Front Door frontend endpoint"
